In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 200)
sns.set_theme(style="whitegrid")

ModuleNotFoundError: No module named 'seaborn'

In [3]:
import os
print(os.getcwd())

C:\Users\Lenovo\PyCharmMiscProject

In [4]:
df = pd.read_csv(
    "occurrences.csv",
    sep=";",
    dtype=str,
    low_memory=False,
    encoding="utf-8"
)

df.head()

,Occurrence_Id,Local_Date_Main_Event,Date_Main_Event_Unconfirmed,Year_Reported,Occurrence_Severity,Main_Event_L1,Main_Event_L2,Main_Event_L3,Not_Vessel_Operations,Short_Description,...,Weather,Wind_Force,Publication_Date,Publication_No,Publication_Type,Published_Report_Website_Link,Occurrence_Record_Modified_On,Last_Updated_At,Occurrences_Reported_From,Occurrences_Reported_To
0,1f59ae23-e48f-ec11-b400-000d3a874c7b,2022-02-01,No,2022,Marine Incident,Contact,Shore Object,NaN,False,A ro-ro cargo vessel made contact with quay side,...,Unknown,Beaufort scale: Unknown,NaN,NaN,NaN,NaN,2026-01-29,2026-05-15,2020-01-01,2025-12-31
1,c51366b7-39cd-ec11-a7b6-0022481a81f8,2022-04-01,No,2022,Marine Incident,Damage / Loss Of Equipment,NaN,NaN,False,A service vessel drifted from a quayside resul...,...,Clear,4 - Moderate Breeze - knot (11-16) m/s (6-8),NaN,NaN,NaN,NaN,2025-03-28,2026-05-15,2020-01-01,2025-12-31
2,883d7a39-90e1-ec11-bb3d-000d3a0cda10,2022-05-01,No,2022,Marine Incident,Accident to person(s),NaN,NaN,False,A inland passenger vessel passenger fell down ...,...,Unknown,Beaufort scale: Unknown,NaN,NaN,NaN,NaN,2026-03-13,2026-05-15,2020-01-01,2025-12-31
3,68afeb11-12ee-ec11-bb3c-000d3a0d2897,2022-06-01,No,2022,Marine Incident,Loss Of Control,Loss Of Propulsion Power,NaN,False,Fishing vessel's gearbox failed resulting in a...,...,Unknown,Beaufort scale: Unknown,NaN,NaN,NaN,NaN,2026-01-29,2026-05-15,2020-01-01,2025-12-31
4,d40d9f19-bd0c-ed11-b83d-0022481b1890,2022-07-01,No,2022,Less Serious,Accident to person(s),NaN,NaN,False,A sailing yacht crew member sustained a partia...,...,Unknown,Beaufort scale: Unknown,NaN,NaN,NaN,NaN,2026-02-23,2026-05-15,2020-01-01,2025-12-31

In [5]:
df.shape
df.head(3)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8599 entries, 0 to 8598
Data columns (total 37 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Occurrence_Id                  8599 non-null   str
 1   Local_Date_Main_Event          8599 non-null   str
 2   Date_Main_Event_Unconfirmed    8599 non-null   str
 3   Year_Reported                  8599 non-null   str
 4   Occurrence_Severity            8599 non-null   str
 5   Main_Event_L1                  8597 non-null   str
 6   Main_Event_L2                  4248 non-null   str
 7   Main_Event_L3                  309 non-null    str
 8   Not_Vessel_Operations          8599 non-null   str
 9   Short_Description              8599 non-null   str
 10  Description                    8599 non-null   str
 11  National_Keywords              132 non-null    str
 12  EMCIP_Keywords                 125 non-null    str
 13  SAR_Intervention               8599 non-null   str
 14  State_Reporting                8599 non-null   str
 15  Occurrence_Location            8598 non-null   str
 16  Coastal_State_Affected         8598 non-null   str
 17  National_Location_L1           7449 non-null   str
 18  National_Location_L2           7167 non-null   str
 19  Latitude                       8598 non-null   str
 20  Longitude                      8598 non-null   str
 21  Lat_Long_Unknown               335 non-null    str
 22  Port_Of_Accident_L1            3251 non-null   str
 23  Port_Of_Accident_L2            2921 non-null   str
 24  Natural_Light                  8599 non-null   str
 25  Sea_State                      8599 non-null   str
 26  Visibility                     8599 non-null   str
 27  Weather                        8599 non-null   str
 28  Wind_Force                     8599 non-null   str
 29  Publication_Date               58 non-null     str
 30  Publication_No                 54 non-null     str
 31  Publication_Type               58 non-null     str
 32  Published_Report_Website_Link  56 non-null     str
 33  Occurrence_Record_Modified_On  8599 non-null   str
 34  Last_Updated_At                8599 non-null   str
 35  Occurrences_Reported_From      8599 non-null   str
 36  Occurrences_Reported_To        8599 non-null   str
dtypes: str(37)
memory usage: 2.4 MB

In [6]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(r"[^a-z0-9]+", "_", regex=True)
      .str.strip("_")
)
df.columns.tolist()

['occurrence_id',
 'local_date_main_event',
 'date_main_event_unconfirmed',
 'year_reported',
 'occurrence_severity',
 'main_event_l1',
 'main_event_l2',
 'main_event_l3',
 'not_vessel_operations',
 'short_description',
 'description',
 'national_keywords',
 'emcip_keywords',
 'sar_intervention',
 'state_reporting',
 'occurrence_location',
 'coastal_state_affected',
 'national_location_l1',
 'national_location_l2',
 'latitude',
 'longitude',
 'lat_long_unknown',
 'port_of_accident_l1',
 'port_of_accident_l2',
 'natural_light',
 'sea_state',
 'visibility',
 'weather',
 'wind_force',
 'publication_date',
 'publication_no',
 'publication_type',
 'published_report_website_link',
 'occurrence_record_modified_on',
 'last_updated_at',
 'occurrences_reported_from',
 'occurrences_reported_to']

In [7]:
date_cols = [
    "local_date_main_event",
    "publication_date",
    "occurrence_record_modified_on",
    "last_updated_at",
    "occurrences_reported_from",
    "occurrences_reported_to"
]

for col in date_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors="coerce")

for col in ["latitude", "longitude", "year_reported"]:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

In [8]:
df.isna().sum().sort_values(ascending=False).head(15)
df["occurrence_severity"].value_counts(dropna=False).head(10)
df["main_event_l1"].value_counts(dropna=False).head(10)

main_event_l1
Accident to person(s)         2381
Damage / Loss Of Equipment    1910
Loss Of Control               1342
Grounding / Stranding          866
Contact                        640
Collision                      526
Fire / Explosion               462
Flooding / Foundering          296
Capsizing / Listing            157
Hull Failure                    10
Name: count, dtype: int64

In [9]:
df.to_csv("occurrences_cleaned.csv", index=False)

In [10]:
df["event_year"] = df["local_date_main_event"].dt.year
df["event_year"].value_counts().sort_index()

event_year
2018       3
2019      18
2020    1215
2021    1499
2022    1256
2023    1592
2024    1514
2025    1502
Name: count, dtype: int64

In [11]:
import pandas as pd

clean_df = pd.read_csv("occurrences_cleaned.csv")
clean_df.shape

(8599, 37)

In [13]:
clean_df = pd.read_csv("occurrences_cleaned.csv", sep=",")
clean_df.shape

(8599, 37)

In [14]:
clean_df.head(5)
clean_df.info()
clean_df.columns.tolist()

<class 'pandas.DataFrame'>
RangeIndex: 8599 entries, 0 to 8598
Data columns (total 37 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   occurrence_id                  8599 non-null   str
 1   local_date_main_event          8599 non-null   str
 2   date_main_event_unconfirmed    8599 non-null   str
 3   year_reported                  8599 non-null   int64
 4   occurrence_severity            8599 non-null   str
 5   main_event_l1                  8597 non-null   str
 6   main_event_l2                  4248 non-null   str
 7   main_event_l3                  309 non-null    str
 8   not_vessel_operations          8599 non-null   bool
 9   short_description              8599 non-null   str
 10  description                    8599 non-null   str
 11  national_keywords              132 non-null    str
 12  emcip_keywords                 125 non-null    str
 13  sar_intervention               8599 non-null   str
 14  state_reporting                8599 non-null   str
 15  occurrence_location            8598 non-null   str
 16  coastal_state_affected         8598 non-null   str
 17  national_location_l1           7449 non-null   str
 18  national_location_l2           7167 non-null   str
 19  latitude                       8598 non-null   float64
 20  longitude                      8598 non-null   float64
 21  lat_long_unknown               335 non-null    str
 22  port_of_accident_l1            3251 non-null   str
 23  port_of_accident_l2            2921 non-null   str
 24  natural_light                  8599 non-null   str
 25  sea_state                      8599 non-null   str
 26  visibility                     8599 non-null   str
 27  weather                        8599 non-null   str
 28  wind_force                     8599 non-null   str
 29  publication_date               58 non-null     str
 30  publication_no                 54 non-null     str
 31  publication_type               58 non-null     str
 32  published_report_website_link  56 non-null     str
 33  occurrence_record_modified_on  8599 non-null   str
 34  last_updated_at                8599 non-null   str
 35  occurrences_reported_from      8599 non-null   str
 36  occurrences_reported_to        8599 non-null   str
dtypes: bool(1), float64(2), int64(1), str(33)
memory usage: 2.4 MB

['occurrence_id',
 'local_date_main_event',
 'date_main_event_unconfirmed',
 'year_reported',
 'occurrence_severity',
 'main_event_l1',
 'main_event_l2',
 'main_event_l3',
 'not_vessel_operations',
 'short_description',
 'description',
 'national_keywords',
 'emcip_keywords',
 'sar_intervention',
 'state_reporting',
 'occurrence_location',
 'coastal_state_affected',
 'national_location_l1',
 'national_location_l2',
 'latitude',
 'longitude',
 'lat_long_unknown',
 'port_of_accident_l1',
 'port_of_accident_l2',
 'natural_light',
 'sea_state',
 'visibility',
 'weather',
 'wind_force',
 'publication_date',
 'publication_no',
 'publication_type',
 'published_report_website_link',
 'occurrence_record_modified_on',
 'last_updated_at',
 'occurrences_reported_from',
 'occurrences_reported_to']

In [15]:
print("raw:", df.shape)
print("clean:", clean_df.shape)

print(df.columns[:10].tolist())
print(clean_df.columns[:10].tolist())

raw: (8599, 38)
clean: (8599, 37)
['occurrence_id', 'local_date_main_event', 'date_main_event_unconfirmed', 'year_reported', 'occurrence_severity', 'main_event_l1', 'main_event_l2', 'main_event_l3', 'not_vessel_operations', 'short_description']
['occurrence_id', 'local_date_main_event', 'date_main_event_unconfirmed', 'year_reported', 'occurrence_severity', 'main_event_l1', 'main_event_l2', 'main_event_l3', 'not_vessel_operations', 'short_description']

In [ ]:
clean_df["event_year"].value_counts().sort_index()
clean_df["occurrence_severity"].value_counts(dropna=False)
clean_df["main_event_l1"].value_counts(dropna=False).head(10)

In [17]:
clean_df.columns.tolist()

['occurrence_id',
 'local_date_main_event',
 'date_main_event_unconfirmed',
 'year_reported',
 'occurrence_severity',
 'main_event_l1',
 'main_event_l2',
 'main_event_l3',
 'not_vessel_operations',
 'short_description',
 'description',
 'national_keywords',
 'emcip_keywords',
 'sar_intervention',
 'state_reporting',
 'occurrence_location',
 'coastal_state_affected',
 'national_location_l1',
 'national_location_l2',
 'latitude',
 'longitude',
 'lat_long_unknown',
 'port_of_accident_l1',
 'port_of_accident_l2',
 'natural_light',
 'sea_state',
 'visibility',
 'weather',
 'wind_force',
 'publication_date',
 'publication_no',
 'publication_type',
 'published_report_website_link',
 'occurrence_record_modified_on',
 'last_updated_at',
 'occurrences_reported_from',
 'occurrences_reported_to']

In [18]:
clean_df["local_date_main_event"] = pd.to_datetime(clean_df["local_date_main_event"], errors="coerce")
clean_df["event_year"] = clean_df["local_date_main_event"].dt.year

In [19]:
clean_df["event_year"].value_counts().sort_index()

event_year
2018       3
2019      18
2020    1215
2021    1499
2022    1256
2023    1592
2024    1514
2025    1502
Name: count, dtype: int64

In [20]:
print(clean_df.columns[:20].tolist())

['occurrence_id', 'local_date_main_event', 'date_main_event_unconfirmed', 'year_reported', 'occurrence_severity', 'main_event_l1', 'main_event_l2', 'main_event_l3', 'not_vessel_operations', 'short_description', 'description', 'national_keywords', 'emcip_keywords', 'sar_intervention', 'state_reporting', 'occurrence_location', 'coastal_state_affected', 'national_location_l1', 'national_location_l2', 'latitude']

In [21]:
clean_df = pd.read_csv("occurrences_cleaned.csv")

In [22]:
clean_df.shape

(8599, 37)

In [23]:
clean_df.head()

,occurrence_id,local_date_main_event,date_main_event_unconfirmed,year_reported,occurrence_severity,main_event_l1,main_event_l2,main_event_l3,not_vessel_operations,short_description,...,weather,wind_force,publication_date,publication_no,publication_type,published_report_website_link,occurrence_record_modified_on,last_updated_at,occurrences_reported_from,occurrences_reported_to
0,1f59ae23-e48f-ec11-b400-000d3a874c7b,2022-02-01,No,2022,Marine Incident,Contact,Shore Object,NaN,False,A ro-ro cargo vessel made contact with quay side,...,Unknown,Beaufort scale: Unknown,NaN,NaN,NaN,NaN,2026-01-29,2026-05-15,2020-01-01,2025-12-31
1,c51366b7-39cd-ec11-a7b6-0022481a81f8,2022-04-01,No,2022,Marine Incident,Damage / Loss Of Equipment,NaN,NaN,False,A service vessel drifted from a quayside resul...,...,Clear,4 - Moderate Breeze - knot (11-16) m/s (6-8),NaN,NaN,NaN,NaN,2025-03-28,2026-05-15,2020-01-01,2025-12-31
2,883d7a39-90e1-ec11-bb3d-000d3a0cda10,2022-05-01,No,2022,Marine Incident,Accident to person(s),NaN,NaN,False,A inland passenger vessel passenger fell down ...,...,Unknown,Beaufort scale: Unknown,NaN,NaN,NaN,NaN,2026-03-13,2026-05-15,2020-01-01,2025-12-31
3,68afeb11-12ee-ec11-bb3c-000d3a0d2897,2022-06-01,No,2022,Marine Incident,Loss Of Control,Loss Of Propulsion Power,NaN,False,Fishing vessel's gearbox failed resulting in a...,...,Unknown,Beaufort scale: Unknown,NaN,NaN,NaN,NaN,2026-01-29,2026-05-15,2020-01-01,2025-12-31
4,d40d9f19-bd0c-ed11-b83d-0022481b1890,2022-07-01,No,2022,Less Serious,Accident to person(s),NaN,NaN,False,A sailing yacht crew member sustained a partia...,...,Unknown,Beaufort scale: Unknown,NaN,NaN,NaN,NaN,2026-02-23,2026-05-15,2020-01-01,2025-12-31

In [24]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8599 entries, 0 to 8598
Data columns (total 37 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   occurrence_id                  8599 non-null   str
 1   local_date_main_event          8599 non-null   str
 2   date_main_event_unconfirmed    8599 non-null   str
 3   year_reported                  8599 non-null   int64
 4   occurrence_severity            8599 non-null   str
 5   main_event_l1                  8597 non-null   str
 6   main_event_l2                  4248 non-null   str
 7   main_event_l3                  309 non-null    str
 8   not_vessel_operations          8599 non-null   bool
 9   short_description              8599 non-null   str
 10  description                    8599 non-null   str
 11  national_keywords              132 non-null    str
 12  emcip_keywords                 125 non-null    str
 13  sar_intervention               8599 non-null   str
 14  state_reporting                8599 non-null   str
 15  occurrence_location            8598 non-null   str
 16  coastal_state_affected         8598 non-null   str
 17  national_location_l1           7449 non-null   str
 18  national_location_l2           7167 non-null   str
 19  latitude                       8598 non-null   float64
 20  longitude                      8598 non-null   float64
 21  lat_long_unknown               335 non-null    str
 22  port_of_accident_l1            3251 non-null   str
 23  port_of_accident_l2            2921 non-null   str
 24  natural_light                  8599 non-null   str
 25  sea_state                      8599 non-null   str
 26  visibility                     8599 non-null   str
 27  weather                        8599 non-null   str
 28  wind_force                     8599 non-null   str
 29  publication_date               58 non-null     str
 30  publication_no                 54 non-null     str
 31  publication_type               58 non-null     str
 32  published_report_website_link  56 non-null     str
 33  occurrence_record_modified_on  8599 non-null   str
 34  last_updated_at                8599 non-null   str
 35  occurrences_reported_from      8599 non-null   str
 36  occurrences_reported_to        8599 non-null   str
dtypes: bool(1), float64(2), int64(1), str(33)
memory usage: 2.4 MB

In [25]:
print("Shape:", clean_df.shape)
print("\nColumns:", clean_df.columns.tolist()[:20])
print("\nHead:")
display(clean_df.head())

Shape: (8599, 37)

Columns: ['occurrence_id', 'local_date_main_event', 'date_main_event_unconfirmed', 'year_reported', 'occurrence_severity', 'main_event_l1', 'main_event_l2', 'main_event_l3', 'not_vessel_operations', 'short_description', 'description', 'national_keywords', 'emcip_keywords', 'sar_intervention', 'state_reporting', 'occurrence_location', 'coastal_state_affected', 'national_location_l1', 'national_location_l2', 'latitude']

Head:

,occurrence_id,local_date_main_event,date_main_event_unconfirmed,year_reported,occurrence_severity,main_event_l1,main_event_l2,main_event_l3,not_vessel_operations,short_description,...,weather,wind_force,publication_date,publication_no,publication_type,published_report_website_link,occurrence_record_modified_on,last_updated_at,occurrences_reported_from,occurrences_reported_to
0,1f59ae23-e48f-ec11-b400-000d3a874c7b,2022-02-01,No,2022,Marine Incident,Contact,Shore Object,NaN,False,A ro-ro cargo vessel made contact with quay side,...,Unknown,Beaufort scale: Unknown,NaN,NaN,NaN,NaN,2026-01-29,2026-05-15,2020-01-01,2025-12-31
1,c51366b7-39cd-ec11-a7b6-0022481a81f8,2022-04-01,No,2022,Marine Incident,Damage / Loss Of Equipment,NaN,NaN,False,A service vessel drifted from a quayside resul...,...,Clear,4 - Moderate Breeze - knot (11-16) m/s (6-8),NaN,NaN,NaN,NaN,2025-03-28,2026-05-15,2020-01-01,2025-12-31
2,883d7a39-90e1-ec11-bb3d-000d3a0cda10,2022-05-01,No,2022,Marine Incident,Accident to person(s),NaN,NaN,False,A inland passenger vessel passenger fell down ...,...,Unknown,Beaufort scale: Unknown,NaN,NaN,NaN,NaN,2026-03-13,2026-05-15,2020-01-01,2025-12-31
3,68afeb11-12ee-ec11-bb3c-000d3a0d2897,2022-06-01,No,2022,Marine Incident,Loss Of Control,Loss Of Propulsion Power,NaN,False,Fishing vessel's gearbox failed resulting in a...,...,Unknown,Beaufort scale: Unknown,NaN,NaN,NaN,NaN,2026-01-29,2026-05-15,2020-01-01,2025-12-31
4,d40d9f19-bd0c-ed11-b83d-0022481b1890,2022-07-01,No,2022,Less Serious,Accident to person(s),NaN,NaN,False,A sailing yacht crew member sustained a partia...,...,Unknown,Beaufort scale: Unknown,NaN,NaN,NaN,NaN,2026-02-23,2026-05-15,2020-01-01,2025-12-31